#! /bin/bash

set -e

if [ "$DBPASS" == "" ]; then
    echo "Missing required environment variable: DBPASS"
    exit 1
fi

postgres_data=/var/lib/postgresql/9.1/main

mkdir -p $postgres_data
chown -R postgres:postgres $postgres_data
su postgres -c "/usr/lib/postgresql/9.1/bin/initdb -D $postgres_data"
ln -s /etc/ssl/certs/ssl-cert-snakeoil.pem $postgres_data/server.crt
ln -s /etc/ssl/private/ssl-cert-snakeoil.key $postgres_data/server.key

service postgresql start
cat /var/log/postgresql/*
su postgres -c "psql --command \"CREATE USER canvas WITH NOSUPERUSER NOCREATEDB NOCREATEROLE PASSWORD '${DBPASS}'\""
su postgres -c "createdb canvas_production --owner=canvas"
su postgres -c "createdb canvas_queue_production --owner=canvas"
