#! /bin/bash

set -e

if [ "$DBPASS" == "" ]; then
    echo "Missing required environment variable: DBPASS"
    exit 1
fi

postgres_data=/var/lib/postgresql/9.3/main

if [ "$(ls -A $postgres_data)" ]; then
    echo "DB already initialized"
    exit 0
fi

mkdir -p $postgres_data
chown -R postgres:postgres $postgres_data
su postgres -c "/usr/lib/postgresql/9.3/bin/initdb -D $postgres_data -E 'UTF-8'"
ln -s /etc/ssl/certs/ssl-cert-snakeoil.pem $postgres_data/server.crt
ln -s /etc/ssl/private/ssl-cert-snakeoil.key $postgres_data/server.key

service postgresql start
cat /var/log/postgresql/*

# Need CREATEDB to be able to run tests
su postgres -c "psql --command \"CREATE USER canvas WITH NOSUPERUSER CREATEDB NOCREATEROLE PASSWORD '${DBPASS}'\""
su postgres -c "createdb canvas_production --owner=canvas"
su postgres -c "createdb canvas_queue_production --owner=canvas"
